#!/bin/bash

if test "$#" = "0"; then 
	echo 'direct pt1230 "Unknown" "pt1230 cbdev hackdriver"'
	exit 0
fi

DEVICENODE=${DEVICE_URI#pt1230:}
if [ -z "$DEVICENODE" ]; then
	DEVICENODE="/dev/usb/lp0"
fi

# redirect file arguments to stdin
if test -n "$6"; then
	exec <"$6"
fi

# Pipeline explanation
#	gs		Renders the input postscript to the 64 char wide ASCII 0/1 map
#	tail		Remove ghostscript header
#	pt1230		Actually print the thing
gs -q -dBATCH -dQUIET -dNOPAUSE -sDEVICE=pbm -sOutputFile=- - | tail -n +4 | pt1230 -u -b -d $DEVICENODE
